---
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-symlinks
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/fauust/pre-commit-shfmt
    rev: master
    hooks:
      - id: shell-fmt
        name: Check shell style with shfmt
        args: ["-d", "-ci", "-i", "2"]
        types: ["bash"]
