---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-symlinks
      - id: debug-statements
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: docker-shell-shfmt
        name: Run shfmt with docker
        language: docker_image
        entry: mvdan/shfmt:v3.7.0 -d -i 2 -ci -s
        types: [shell]
