---

language: ruby
sudo: required
rvm:
  - 2.4.3

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      env:
        - TAG='[ dotfiles/packages ]'
        - RUN_LIST=dotfiles
install:
  - rm -f ~/.bashrc
  - brew install shellcheck stow pre-commit

script:
  - make install
  - make test
