---

language: ruby
sudo: required
rvm:
  - 2.3

matrix:
  include:
    - os: osx
      env:
        - TAG='[ base/dotfiles ]'
        - INSTALL_GPGTOOLS=0
        - OS=Darwin
        - RUN_LIST=base,dotfiles
    - os: osx
      env:
        - TAG='[ dev/licensed ]'
        - INSTALL_DOTFILES=0
        - OS=Darwin
        - RUN_LIST=dev
    - os: osx
      env:
        - TAG='[ messaging/multimedia ]'
        - INSTALL_DOTFILES=0
        - OS=Darwin
        - RUN_LIST=messaging,multimedia
install:
  - brew install shellcheck stow pre-commit
  - gem install serverspec

script:
  - ./install.sh
  - make test
