---
language: ruby
sudo: required
rvm:
  - 2.6

cache:
  directories:
    - ${HOME}/.cache/pip
    - ${HOME}/node_modules
    - ${HOME}/Library/Caches/Homebrew

matrix:
  include:
    - os: osx
      osx_image: xcode11.2
      env:
        - TAG='[ dotfiles/packages ]'
        - RUN_LIST=dotfiles
        - PATH=${HOME}/.homebrew/bin:${HOME}/bin:${PATH}
    - os: osx
      osx_image: xcode11.2
      env:
        - TAG='[ privacy/packages ]'
        - RUN_LIST=privacy
        - PATH=${HOME}/.homebrew/bin:${HOME}/bin:${PATH}

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"

before_cache:
  - brew cleanup

before_install:
  - rm -f ${HOME}/.bashrc ${HOME}/.gitconfig
  - mkdir -p ${HOME}/bin
  - curl -L https://github.com/mvdan/sh/releases/download/v3.1.0/shfmt_v3.1.0_darwin_amd64 -o ${HOME}/bin/shfmt
  - chmod u+x ${HOME}/bin/shfmt
  - pip install virtualenv

install:
  - make install-dev

script:
  - make install
  - make test
