---
language: ruby
sudo: required
rvm:
  - 2.6

matrix:
  include:
    - os: osx
      osx_image: xcode11.2
      env:
        - TAG='[ dotfiles/packages ]'
        - RUN_LIST=dotfiles
        - PATH=${HOME}/.homebrew/bin:${PATH}
    - os: osx
      osx_image: xcode11.2
      env:
        - TAG='[ privacy/packages ]'
        - RUN_LIST=privacy
        - PATH=${HOME}/.homebrew/bin:${PATH}

addons:
  apt:
    update: true
    packages:
      - "python3"
      - "python3-pip"

install:
  - rm -f ${HOME}/.bashrc ${HOME}/.gitconfig
  - pip install virtualenv
  - make install-dev

script:
  - make install
  - make test
