---

language: ruby
sudo: required

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      ruby: 2.2
      env:
        - TAG='[ base/dotfiles ]'
        - INSTALL_GPGTOOLS=0
        - OS=darwin
        - RUN_LIST=base,dotfiles
    - os: osx
      osx_image: xcode7.3
      ruby: 2.2
      env:
        - TAG='[ dev/licensed ]'
        - INSTALL_DOTFILES=0
        - OS=darwin
        - RUN_LIST=dev
    - os: osx
      osx_image: xcode7.3
      ruby: 2.2
      env:
        - TAG='[ messaging/multimedia ]'
        - INSTALL_DOTFILES=0
        - OS=Darwin
        - RUN_LIST=messaging,multimedia
install:
  - brew install shellcheck stow
  - gem install serverspec

script:
  - ./install.sh
  - make test
