---

language: ruby
sudo: required
rvm:
  - 2.6

matrix:
  include:
    - os: osx
      osx_image: xcode11.2
      env:
        - TAG='[ dotfiles/packages ]'
        - RUN_LIST=dotfiles
        - PATH=/Users/travis/.homebrew/bin:${PATH}
install:
  - rm -f ~/.bashrc ~/.gitconfig
  - brew install shellcheck pre-commit
  - make install-gems

script:
  - make install
  - make test
