---
extends: default

rules:
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  comments-indentation: disable
  comments:
    require-starting-space: false
    min-spaces-from-content: 1
  indentation:
    spaces: 2
  line-length:
    max: 120
    level: warning
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
  truthy:
    allowed-values:
      - "true"
      - "false"
